### ISSUE TITLE
Get a Deloitte badge on the page

### ISSUE THREAD

**Issue by VonSub** [threefoldtech/www_threefold_tech#60]
@maximilianrang shot me the idea of bringing a badge to the page that show's we where part of the Deloitte Fast 50

**Comment by samtaggart** [comment]
@VonSub Should still do this!

**Comment by samtaggart** [comment]
@VonSub Maybe should point to this issue from an issue you can create in Web 2.7 so that we get it on a project. Can put it in home_private.

**Comment by VonSub** [comment]
![image](https://user-images.githubusercontent.com/29431263/112498607-faee7e00-8d86-11eb-972a-8de07b0c3e83.png)

Mockup for graphic plus placement

**Comment by VonSub** [comment]
Texts:

Title: Recognized Innovators
Subtitle: ThreeFold Tech was nominated as Rising Star by Deloitte.

**Comment by VonSub** [comment]
Image: 
![Uploading deloitte-image.png…]()

**Comment by ehab-hassan** [comment]
I need the image this link not working

**Comment by samtaggart** [comment]
![Fast50 BELGIUM PRI CMYK_2020-Del Logo-on black](https://user-images.githubusercontent.com/50134479/112809043-499b6100-9082-11eb-9dc5-7adcc8ee1b3f.jpg)

**Comment by samtaggart** [comment]
@ehab-hassan Here you go brother.

**Comment by VonSub** [comment]
@samtaggart should've updated, I already sent @ehab-hassan a png.
I just noticed the "Belgium" has fallen off of that .png so will regenerate.
